### PR TITLE
Added parser exception handlers

### PR DESCRIPTION
**Pull request by dpnishant**
Added exception handlers while parsing/scanning to skip files with syntax errors while scanning .js files in bulk.

### CODE REVIEW

**Comment by mozfreddyb** [comment]
Sweet! How would this look like in the Web UI, @dpnishant?

**Comment by mozfreddyb** [comment]
(I am concerned that if I merge this pull request, that it might be removed in @zombie's upcoming big merge & split of all things.)

**Comment by dpnishant** [comment]
Hi @mozfreddyb here is another change that I have done for myself (https://github.com/dpnishant/raptor/blob/master/backend/scanjs/scanner.js#L31-L49) i.e. skipping known JS library files while scanning.

**Comment by mozfreddyb** [comment]
That's a nice idea!
If you are a security researcher, I totally get that you want to skip well-known files.

If you are a code reviewer that decides whether to publish on Firefox Marketplace or addons.mozilla.org, you don't want to give the code authors a backdoor to avoid all checks though.

Maybe this should be a commandline (and webui) option).
What do you think?

**Comment by dpnishant** [comment]
Yes, agreed. We can make it optional via a command-line switch. If you are OK, I can send the combined PR in sometime.

**Comment by mozfreddyb** [comment]
Yeah, please do! (but not in this one :))

**Pull request merged**
